version: "3"

services:
  mongodb:
    image: mongo
    command: [--auth]
    container_name: backend-mongo
    restart: always
    volumes:
      - ./.docker/mongo/data/:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopassw
      - MONGODB_USER=root
      - MONGODB_PASS=mongopassw
