version: "3"

services:
  mongodb:
    image: mongo
    command: [--auth]
    container_name: backend-mongo
    restart: always
    volumes:
      - ./.docker/mongo/data/:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${process.env.MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${process.env.MONGO_PASSWORD}
      - MONGODB_USER=${process.env.MONGO_USERNAME}
      - MONGODB_PASS=${process.env.MONGO_PASSWORD}
